hexchat: Autospec creation for update from version 2.14.3 to version 2.16.0
A_D (3):
      python: Various cffi fixes
      python: Made sure to set sys.argv if it is not set. fixes #2282
      python: plugin cleanup and refactor

Alexandre Jousset (1):
      python: Fix off by one range

Andrew Rodland (1):
      Merge pull request #1457 from arodland/forgiving-ctcp

Bakasura (1):
      FiSHLiM: Support for CBC mode + more commands (#2347)

BakasuraRCE (9):
      fishlim: Fix cast
      fishlim: Fix result
      fishlim: Remove needless functions for tests
      fishlim: Remove compiler warnings
      fishlim: Remove needless header
      fishlim: Implement correct handling of long and UTF-8 messages
      plugin interface: Refactor "flags" option in "channels" list to be more clear with bit operators
      notification: Implement notification option for channels
      plugin interface: :lipstick:

Ben Harris (1):
      add tilde.chat

DasBrain (1):
      Place ChanServ notices in the front buffer if the front buffer is on the same network.

DjLegolas (7):
      Fixed proxy user/password buffer overflow
      Change Inno path property
      Updated Toolset to v142
      Fixed notifications-winrt compilation error
      Update github workflows
      ci: fixed Inno Download Plugin download path
      ci: fixed python paths

Filippo Cortigiani (1):
      Added SimosNap to server list (#2349)

Itsuki Toyota (1):
      Fetch latest .po files

James Clarke (1):
      Avoid prioritising MODE queries for channels with hyphens in their name

Jan Harasym (1):
      Add "DarkScience" to default server list. (#2474)

Jared Shields (1):
      Update servlist.c

John Levon (1):
      Use pango_font_metrics_get_height() to calculate font height (#2500)

Jonathan (1):
      Remove Moznet

Lorenzo Ancora (1):
      Add the official EU server to hackint network (#2495)

Martin Weinelt (1):
      servlist: add hackint irc network

Mateusz Gozdek (1):
      plugins/lua/lua.c: fix segfault on lua_pop with Lua 5.4.3

Mattia Rizzolo (1):
      Fix compilation failure on non-linux, non-darwin, non-windows systems.

Michael Catanzaro (1):
      Avoid direct use of libproxy

Miguel (1):
      Update ptnet servers (#2205)

Mike Skec (1):
      url.c: add gemini & gopher parsing

Panagiotis Vasilopoulos (1):
      Add Libera Chat to network list

Patrick (6):
      Try building with lgtm
      Create FUNDING.yml
      readme: Remove build status badges
      Remove 2ch from network list
      servlist: Add ICQ-Chat
      servlist: Remove freenode

Patrick Griffis (35):
      sysinfo: Add support for /etc/os-release
      sysinfo: Fixup formatting
      Fix new stringop-truncation warnings
      build: Silence some Meson warnings and bump requirement to 0.40.0
      Use prefix variable in pkgconfig file
      python: Rewrite with CFFI
      python: Fix console not eating commands
      Revert "Create FUNDING.yml"
      Switch to Github Actions for Linux CI
      Fix capability negotiation ending before sasl finishes with multi-line cap
      Follow more modern conventions for USER message
      build: Fix some meson warnings
      Bump version to 2.14.3
      appdata: Add OARS information
      build: Better support building against python 3.8+
      build: Fix potential undefined variable
      Fix parsing of 313
      Increase max number of words a line can be split into
      Revert word array length change
      Better handle various ctime() calls failing
      Change default network to Libera.Chat
      Always pass a valid URI to gtk_show_uri()
      actions: Upload windows artifacts for each arch
      actions: Add flatpak action
      actions: Remove default value in ubuntu build
      Fix allowed characters when escaping URIs
      build: Misc cleanup of options
      actions: Build on Ubuntu 20.04
      Remove libnotify dependency
      Fix whitespace issues
      fish: Misc test cleanups
      actions: Add MSYS2 builder
      Explicitly set app icon in notifications
      win32: Update to OpenSSL 1.1
      Bump version to 2.16.0

Paul Wise (2):
      Add a channel context menu item to focus channels
      Hide Focus Channel when the selected channel is already focussed

Ryan Schmidt (1):
      Fix user list not tracking mode changes

Sadie Powell (17):
      Add a workaround for icons not scaling right on HiDPI screens. (#2573)
      Implement support for the IRCv3 SETNAME specification. (#2571)
      Implement support for the IRCv3 invite-notify specification. (#2574)
      Implement support for the IRCv3 account-tag specification. (#2572)
      Parse the output of the 005 numeric correctly. (#2585)
      Implement support for the IRCv3 UTF8ONLY specification.
      Default new servers to use TLS if built with OpenSSL.
      Require opting out of SSL verification in /server and /reconnect.
      Switch back to using newserver as the default server name.
      Consistently set the SSL state in /reconnect.
      Replace identify-msg support with solanum.chat/identify-msg.
      Implement support for strikethrough text.
      Implement generic support for IRCv3 standard replies. (#2589)
      Fix parsing +beI lists on InspIRCd.
      Remove some weird guesswork on the 004 numeric. (#2621)
      Increase the linebuf length to fit a full message including tags.
      Be a bit less insulting about servers with longer line lengths.

Sbgodin (1):
      python: Fix exception with list_pluginpref()

Simon Levermann (1):
      Ignore some non-interesting filesystem types

Stepan Broz (2):
      Make dcc_ip being a per-server value.
      Fix a typo-error in src/common/hexchat.h:485 "haxchatprefs" -> "hexchatprefs"

Tim Gates (1):
      docs: fix simple typo, wory -> worry

Valerie Pond (1):
      servlist: Add back TURLINet (#2602)

Xandrah (1):
      Update servlist.c (#2522)

Zach Bacon (1):
      Add missing winuser.h include for mingw (#2403)

adamus1red (1):
      Add DigitalIRC to default servlist.c

cajuncooks (1):
      Extend input box GTK theme workaround to include Yaru

cranberry (1):
      Adding LibertaCasa + TripSit to servlist.c (#2538)

delthas (4):
      win32: Replace include of winuser.h with windows.h
      win32: Fix building executables with invalid entrypoints
      win32: Disable ASLR for Windows debug builds
      win32: Fix undefined symbol for builds with -with-plugin=false

dimitrisdm (1):
      Add ACN IRC Network (#2524)

jacob1 (1):
      Python: Fix error in hexchat.emit_print when passing time attribute

jesopo (1):
      SASL EXTERNAL doesn't necessitate a certificate

kelek- (1):
      Updated the maximum length of the socks5 user and password to comply to RFC 1929, where both the password and the username length is definied as a maximum of 255

linuxdaemon (3):
      python: Make the plugins table dynamically sized (#2291)
      python: Make sure `help()` doesn't cause hexchat to hang (#2290)
      Remove : from various trailing parameters (#2301)

moon (1):
      Update servlist.c - Network clean up (#2597)

nia (1):
      build: Make generated headers a dependency for users of common.

pkubaj (1):
      Fix build on FreeBSD